### ISSUE TITLE
NestedList uupdateTitleText should be boolean instead of string

### ISSUE THREAD

**Issue by gryffindor14** [ahome-it/ahome-touch#10]
public native void setUpdateTitleText(String value) /*-{
		var nestedlist = this.@com.ait.toolkit.sencha.touch.client.core.Component::getOrCreateJsObj()();
		nestedlist.setUpdateTitleText(value);
	}-*/;

value should be a boolean instead of a string. Getter works correctly

**Comment by eemi2010** [comment]
Fixed in Master : https://github.com/ahome-it/ahome-touch/commit/6f67286b4617d0fbb8115986f1abc94801887f7d.
Thx.
