### ISSUE TITLE
ListView setGrouped uses setAttribute rather than _setGrouped fuction

### ISSUE THREAD

**Issue by gryffindor14** [ahome-it/ahome-touch#11]
public void setGrouped(boolean value) {
		this.setAttribute("grouped", value, true);
	}

should instead be 

public void setGrouped(boolean value) {
		_setGrouped(value);
	}

**Comment by eemi2010** [comment]
Thx. Fixed here https://github.com/ahome-it/ahome-touch/commit/59b5a7df95a3cb22d9da657fcdf2bd6a3a145652
