### ISSUE TITLE
Bug: toggleChangeHandler

### ISSUE THREAD

**Issue by roman-e** [ahome-it/ahome-touch#13]
Hi

I've found a bug in the ToggleChangeHandler.

1. In the method addToggleChangeHandler in the Toggle class, you get a CheckBox component instead of Toggle. (See line 117 in the class Toggle)

2. The change event of a toggle control returns the values as integers instead of booleans, so the properties newValue and value of ToggleChangeEvent class need to be changed.
(see: http://docs.sencha.com/touch/2.4/2.4.2-apidocs/#!/api/Ext.field.Toggle-event-change)

After these  changes, the toggleChangeEvent works fine.

**Comment by eemi2010** [comment]
Thx for reporting. Fixed in https://github.com/ahome-it/ahome-touch/commit/97ba4dec2921769fc73828b3c221d0bc788fac91
