### ISSUE TITLE
Text field has changeevent parameters reversed

### ISSUE THREAD

**Issue by gryffindor14** [ahome-it/ahome-touch#8]
for the text field OnChange function the oldValue and newValue parameters are reversed. 

Line 289
var fn = function(t, n, o) {

should be 
var fn = function(t,o,n){

**Comment by eemi2010** [comment]
Thx. Will fix in  asap.

**Comment by eemi2010** [comment]
Fixed in : https://github.com/ahome-it/ahome-touch/commit/775cfd1549eb797d4103f429cfed76db3758b876
