### ISSUE TITLE
HandlerRegistration widget is undefined 

### ISSUE THREAD

**Issue by gryffindor14** [ahome-it/ahome-touch#9]
In handler Registration the call to unregister 

var target = this.@com.ait.toolkit.sencha.touch.client.events.HandlerRegistration::getTarget()();
var targetJs = widget.@com.ait.toolkit.sencha.touch.client.core.Component::getOrCreateJsObj()();

widget is undefined. Should be target 

var target = this.@com.ait.toolkit.sencha.touch.client.events.HandlerRegistration::getTarget()();
var targetJs = target.@com.ait.toolkit.sencha.touch.client.core.Component::getOrCreateJsObj()();

**Comment by eemi2010** [comment]
Fixed in Master: https://github.com/ahome-it/ahome-touch/commit/ef27855dc52b31df6c09197e1a9185c4d44f1f14
